app = "anonxmusic-7684pw"
primary_region = "iad"

# أمر التشغيل يعتمد على الدوكر مباشرة
[processes]
  app = ""

[[vm]]
  cpu_kind = "shared"
  cpus = 2           # خليتها 2 كور عشان تستحمل الرامات العالية
  memory_mb = 5120   # 5 جيجا (الكمبيوتر بيحسب الـ 5000 كـ 5120 ميجا)
